# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_-DZlaDmjjQCWHZ202xuP9oTWWCDvO2o
"""

import pandas as pd

jadval={
"ism":["Shahnoza", "Ali"],
"familiya":["Tolibova", "Aliyev"],
"yoshi":[19, 20],
"manzili":["Farğona shahar", "Qo`qon shahri"]


}
baza=pd.DataFrame(jadval)
print(baza)

filtr=baza[baza["yoshi"]<20]
print(filtr)

filtr=baza[baza["manzili"]=="Farģona shahar"]
print(filtr)

titanik=pd.read_csv("/content/tested (1).csv")
print(titanik)

filtr=titanik[titanik['Age']<15]
print(filtr)

import pandas as pd

jadval={
"ism":["Shahnoza", "Ali"],
"familiya":["Tolibova", "Aliyev"],
"yoshi":[19, 20],
"manzili":["Farğona shahar", "Qòqon shahar"]


}
baza=pd.DataFrame(jadval)
#print(baza)

#filtr=baza[baza["yoshi"]<20]
#print(filtr)

#filtr=baza[baza["manzili"]=="Farģona shahar"]
#print(filtr)

#titanik=pd.read_csv("/content/tested (1).csv")
#print(titanik)

#filtr=titanik[titanik['Age']<15]
#print(filtr)

def kasallik (belgi):
    if belgi=="Isitma":
      return "Parasetamol iching"
    elif belgi=="Bosh oģriģi":
      return "Bolnol iching"
    elif belgi=="Tomoq oģrigi":
      return "Mukaltin iching"
    else:
      return "Shifokorga murojaat qiling"
belgi=input("kasallik belgisini kiriting")
natija=kasallik(belgi)
print (natija)

def kitob_tavsiya(janr):
   if janr == "Detektiv":
      return "Sherlok Xolms kitobini o'qing"
   elif janr == "Romantika":
      return "O'tkan kunlar kitobini o'qing"
   elif janr == "Fantastika":
      return "Garri Potter kitobini o'qing"
   elif janr == "Ilmiy":
      return "Sun'iy intellekt  asoslari kitobini o'qing"
   else:
      return "Kutubxonaga murojaat qiling"
janr = input("Qanday janrdagi kitob kerak? ")
natija = kitob_tavsiya(janr)
print(natija)

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,6])
y=np.array([0,250])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,6,250])
y=np.array([0,250,250])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,0,6,6])
y=np.array([0,250,250,6])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,0,6,6,0])
y=np.array([0,250,250,0,0])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array ([0,0,5,0])
y=np.array([0,200,125,0])
plt.plot(x,y, 'd--y')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x1=np.array([1,1,12,12,1])
y1=np.array([1,7,7,1,1])
x2=np.array([1,12])
y2=np.array([3,3])
x3=np.array([1,12])
y3=np.array([5,5])

x16=np.array([1,1,12,12])
y16=np.array([5,7,7,5])
x17=np.array([1,1,12,12])
y17=np.array([1,3,3,1])
x18=np.array([2])
y18=np.array([6])
x19=np.array([2.5])
y19=np.array([6])
x4=np.array([5])
y4=np.array([6.5])
x5=np.array([4.5])
y5=np.array([6.5])
x6=np.array([4])
y6=np.array([6.5])
x7=np.array([5])
y7=np.array([6.1])
x8=np.array([4])
y8=np.array([6.1])
x9=np.array([3.5])
y9=np.array([6.1])
x10=np.array([4.5])
y10=np.array([6.1])
x11=np.array([5])
y11=np.array([5.7])
x12=np.array([4.5])
y12=np.array([5.7])
x13=np.array([4])
y13=np.array([5.7])
x14=np.array([3.5])
y14=np.array([5.7])
x15=np.array([3])
y15=np.array([5.7])

plt.fill(x16,y16,color='#0099B5')
plt.fill(x17,y17,color='#1EB53A')
plt.plot(x16,y16)
plt.plot(x18,y18,ms=45 ,marker='o', color='white')
plt.plot(x19,y19,ms=45 ,marker='o', color='#0099B5')

plt.plot(x17,y17)

plt.plot(x4,y4,'*',x5,y5,'*',x6,y6,'*',x7,y7,'*',x8,y8,'*',x9,y9,'*',x10,y10,'*',x11,y11,'*',x12,y12,'*',x13,y13,'*',x14,y14,'*',x15,y15,'*',color='white')
plt.plot(x1,y1)

plt.plot(x2,y2,x3,y3,color='#CE1126')
plt.show()

x_bg = np.array([0, 0, 12, 12])
y_bg = np.array([0, 6, 6, 0])
plt.fill(x_bg, y_bg, color='#E30A17')  # Turkiya qizil rangi

theta = np.linspace(0, 2*np.pi, 100)
r_outer = 1.5
r_inner = 1.0
cx, cy = 6, 3

x_outer = chhx + r_outer * np.cos(theta)
y_outer = cy + r_outer * np.sin(theta)

x_inner = cx + r_inner * np.cos(theta)
y_inner = cy + r_inner * np.sin(theta)

plt.fill(x_outer, y_outer, color='white')
plt.fill(x_inner, y_inner, color='#E30A17')  # qizil bilan ichki qirqish

star_cx, star_cy = 7.5, 3  # yulduz markazi
star_r = 0.8

star_angles = np.linspace(0, 2*np.pi, 6)[:-1]  # 5 burchak
x_star = star_cx + star_r * np.sin(star_angles + np.pi/2)
y_star = star_cy + star_r * np.cos(star_angles + np.pi/2)
plt.fill(x_star, y_star, color='white')

plt.axis('equal')
plt.axis('off')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([1,1,12,12,1])
y=np.array([1,7,7,1,1])
plt.show()
plt.fill(x,y,color='red')
x1=np.array([2])
y1=np.array([6])
x2=np.array([3.5])
y2=np.array([6.5])
plt.plot(x2,y2,ms=15 ,marker='*', color='yellow')
plt.plot(x1,y1,ms=50 ,marker='*', color='yellow')
plt.show()

x=np.array([1,1,12,12,1])
y=np.array([1,7,7,1,1])
plt.show()
plt.fill(x,y,color='red')
x1=np.array([2])
y1=np.array([6])
x2=np.array([3.5])
y2=np.array([6.5])
plt.plot(x2,y2,ms=15 ,marker='*', color='yellow')
x3=np.array([3.8])
y3=np.array([5.5])
plt.plot(x3,y3,ms=15 ,marker='*', color='yellow')
x4=np.array([3.3])
y4=np.array([5.2])
x5=np.array([3.8])
y5=np.array([6.0])
plt.plot(x5,y5,ms=15,marker='*', color='yellow')
plt.plot(x4,y4,ms=15,marker='*', color='yellow')
plt.plot(x1,y1,ms=50 ,marker='*', color='yellow')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([1,1,12,12,1])
y = np.array([1,7,7,1,1])
plt.fill(x, y, color='red')

x1 = np.array([2])
y1 = np.array([6])
plt.plot(x1, y1, ms=50, marker='*', color='yellow')

x2 = np.array([3.5])
y2 = np.array([6.5])
plt.plot(x2, y2, ms=15, marker='*', color='yellow')

x3 = np.array([3.8])
y3 = np.array([5.5])
plt.plot(x3, y3, ms=15, marker='*', color='yellow')

x4 = np.array([3.3])
y4 = np.array(kkk[5.2])
plt.plot(x4, y4, ms=15, marker='*', color='yellow')

plt.axis('equal')
plt.axis('off')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([1,1,12,12,1])
y=np.array([1,7,7,1,1])
plt.show()
plt.fill(x,y,color='red')
x1=np.array([7.8])
y1=np.array([4])

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([1, 1, 12, 12, 1])
y = np.array([1, 7, 7, 1, 1])
plt.fill(x, y, color='red')

t = np.linspace(0, 2*np.pi, 100)


x_white = 4.5 + 1.8 * np.cos(t)
y_white = 4 + 1.8 * np.sin(t)
plt.fill(x_white, y_white, color='white')


x_red = 5.0 + 1.4 * np.cos(t)
y_red = 4 + 1.4 * np.sin(t)
plt.fill(x_red, y_red, color='red')

x_star = np.array([7.5])
y_star = np.array([4])
plt.plot(x_star, y_star, ms=45, marker='*', color='white', linestyle='None')

plt.axis('equal')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x1=np.array([1,1,12,12,1])
y1=np.array([1,7,7,1,1])
x2=np.array([1,12])
y2=np.array([3,3])
x3=np.array([1,12])
y3=np.array([5,5])

x16=np.array([1,1,12,12])
y16=np.array([5,7,7,5])
x17=np.array([1,1,12,12])
y17=np.array([1,3,3,1])
x18=np.array([2])
y18=np.array([6])
x19=np.array([2.5])
y19=np.array([6])
x4=np.array([5])
y4=np.array([6.5])
x5=np.array([4.5])
y5=np.array([6.5])
x6=np.array([4])
y6=np.array([6.5])
x7=np.array([5])
y7=np.array([6.1])
x8=np.array([4])
y8=np.array([6.1])
x9=np.array([3.5])
y9=np.array([6.1])
x10=np.array([4.5])
y10=np.array([6.1])
x11=np.array([5])
y11=np.array([5.7])
x12=np.array([4.5])
y12=np.array([5.7])
x13=np.array([4])
y13=np.array([5.7])
x14=np.array([3.5])
y14=np.array([5.7])
x15=np.array([3])
y15=np.array([5.7])

plt.fill(x16,y16,color='black')
plt.fill(x17,y17,color='yellow')
plt.plot(x16,y16)
plt.plot(x18,y18,ms=45 ,marker='o', color='black')
plt.plot(x19,y19,ms=45 ,marker='o', color='black')

plt.plot(x17,y17)
x_red = np.array([1, 1, 12, 12])
y_red = np.array([3, 5, 5, 3])
plt.fill(x_red, y_red, color='#FF0000') # Sof qizil rang

plt.plot(x4,y4,'*',x5,y5,'*',x6,y6,'*',x7,y7,'*',x8,y8,'*',x9,y9,'*',x10,y10,'*',x11,y11,'*',x12,y12,'*',x13,y13,'*',x14,y14,'*',x15,y15,'*',color='black')

plt.show()

import matplotlib.pyplot as plt
import numpy as np
x1=np.array([1,1,12,12,1])
y1=np.array([1,7,7,1,1])
x2=np.array([1,12])
y2=np.array([3,3])
x3=np.array([1,12])
y3=np.array([5,5])

x16=np.array([1,1,12,12])
y16=np.array([5,7,7,5])
x17=np.array([1,1,12,12])
y17=np.array([1,3,3,1])
x18=np.array([2])
y18=np.array([6])
x19=np.array([2.5])
y19=np.array([6])
x4=np.array([5])
y4=np.array([6.5])
x5=np.array([4.5])
y5=np.array([6.5])
x6=np.array([4])
y6=np.array([6.5])
x7=np.array([5])
y7=np.array([6.1])
x8=np.array([4])
y8=np.array([6.1])
x9=np.array([3.5])
y9=np.array([6.1])
x10=np.array([4.5])
y10=np.array([6.1])
x11=np.array([5])
y11=np.array([5.7])
x12=np.array([4.5])
y12=np.array([5.7])
x13=np.array([4])
y13=np.array([5.7])
x14=np.array([3.5])
y14=np.array([5.7])
x15=np.array([3])
y15=np.array([5.7])

plt.fill(x16,y16,color='white')
plt.fill(x17,y17,color='red')
plt.plot(x16,y16)
plt.plot(x18,y18,ms=45 ,marker='o', color='white')
plt.plot(x19,y19,ms=45 ,marker='o', color='white')

plt.plot(x17,y17)
x_red = np.array([1, 1, 12, 12])
y_red = np.array([3, 5, 5, 3])
plt.fill(x_red, y_red, color='blue')

plt.plot(x4,y4,'*',x5,y5,'*',x6,y6,'*',x7,y7,'*',x8,y8,'*',x9,y9,'*',x10,y10,'*',x11,y11,'*',x12,y12,'*',x13,y13,'*',x14,y14,'*',x15,y15,'*',color='white')

plt.show()

import matplotlib.pyplot as plt
import numpy as np
x1=np.array([1,1,12,12,1])
y1=np.array([1,7,7,1,1])
x2=np.array([1,12])
y2=np.array([3,3])
x3=np.array([1,12])
y3=np.array([5,5])

x16=np.array([1,1,12,12])
y16=np.array([5,7,7,5])
x17=np.array([1,1,12,12])
y17=np.array([1,3,3,1])
x18=np.array([2])
y18=np.array([6])
x19=np.array([2.5])
y19=np.array([6])
x4=np.array([5])
y4=np.array([6.5])
x5=np.array([4.5])
y5=np.array([6.5])
x6=np.array([4])
y6=np.array([6.5])
x7=np.array([5])
y7=np.array([6.1])
x8=np.array([4])
y8=np.array([6.1])
x9=np.array([3.5])
y9=np.array([6.1])
x10=np.array([4.5])
y10=np.array([6.1])
x11=np.array([5])
y11=np.array([5.7])
x12=np.array([4.5])
y12=np.array([5.7])
x13=np.array([4])
y13=np.array([5.7])
x14=np.array([3.5])
y14=np.array([5.7])
x15=np.array([3])
y15=np.array([5.7])

plt.fill(x16,y16,color='red')
plt.fill(x17,y17,color='green')
plt.plot(x16,y16)
plt.plot(x18,y18,ms=45 ,marker='o', color='red')
plt.plot(x19,y19,ms=45 ,marker='o', color='red')

plt.plot(x17,y17)
x_red = np.array([1, 1, 12, 12])
y_red = np.array([3, 5, 5, 3])
plt.fill(x_red, y_red, color='white')

plt.plot(x4,y4,'*',x5,y5,'*',x6,y6,'*',x7,y7,'*',x8,y8,'*',x9,y9,'*',x10,y10,'*',x11,y11,'*',x12,y12,'*',x13,y13,'*',x14,y14,'*',x15,y15,'*',color='red')

plt.show()

from gtts import gTTS
import os
text="Assalomu alaykum hurmatli talabalar"
language="tr"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_tr.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS

!pip install gtts

from gtts import gTTS
import os
text="Assalomu alaykum hurmatli talabalar"
language="tr"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_tr.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men 620.24-guruh talabasi Mòsinova Manzura bòlaman"
language="tr"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_tr.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men 620.24-guruh talabasi Mòsinova Manzura bòlaman"
language="ru"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_ru.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Mòsinova Manzura bòlaman"
language="en"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_en.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Mòsinova Manzura bòlaman"
language="ar"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_ar.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Mòsinova Manzura bòlaman"
language="fr"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_fr.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Mòsinova Manzura bòlaman"
language="zh"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_zh.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Mòsinova Manzura bòlaman"
language="zh-TW"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_zh-TW.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Tolibova Shahnoza bòlaman"
language="de"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_de.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Tolibova Shahnoza bòlaman"
language="es"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_es.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="Assalomu alaykum men Farģona Davlat Texnika Universiteti 620.24-guruh talabasi Tolibova Shahnoza bòlaman"
language="ja"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_file_ja.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)